QUESTIONS = {
    "Python": {
        "Beginner": [
            {"q": "What keyword starts a function in Python?",
             "choices": ["func", "def", "function", "define"], "answer": 1},
            {"q": "Which symbol is used for comments in Python?",
             "choices": ["//", "/*", "#", "--"], "answer": 2},
            {"q": "What does `print('Hello')` do?",
             "choices": ["Saves to file", "Displays Hello", "Returns Hello", "Deletes Hello"], "answer": 1},
            {"q": "What is the output of: 2 + 3 * 2?",
             "choices": ["10", "8", "7", "12"], "answer": 1},
            {"q": "Which data type stores True or False?",
             "choices": ["int", "str", "bool", "float"], "answer": 2},
            {"q": "How do you create a list in Python?",
             "choices": ["{1,2,3}", "(1,2,3)", "[1,2,3]", "<1,2,3>"], "answer": 2},
            {"q": "What does `len([1,2,3])` return?",
             "choices": ["1", "2", "3", "4"], "answer": 2},
            {"q": "Which loop runs while a condition is True?",
             "choices": ["for", "repeat", "while", "loop"], "answer": 2},
        ],
        "Medium": [
            {"q": "What does `range(3)` produce?",
             "choices": ["[1,2,3]", "[0,1,2]", "[0,1,2,3]", "(0,1,2)"], "answer": 1},
            {"q": "What is a Python dictionary?",
             "choices": ["Ordered list", "Key-value store", "Set of values", "Tuple"], "answer": 1},
            {"q": "What does `append()` do to a list?",
             "choices": ["Remove last", "Add to front", "Add to end", "Sort list"], "answer": 2},
            {"q": "What is the result of `'abc'.upper()`?",
             "choices": ["abc", "ABC", "Abc", "Error"], "answer": 1},
            {"q": "Which keyword is used to handle exceptions?",
             "choices": ["catch", "error", "except", "handle"], "answer": 2},
            {"q": "What does `//` do in Python?",
             "choices": ["Comment", "Division", "Floor division", "Power"], "answer": 2},
            {"q": "What is the output of `bool(0)`?",
             "choices": ["True", "False", "0", "None"], "answer": 1},
            {"q": "What does `*args` mean in a function?",
             "choices": ["No args", "One arg", "Variable args", "Keyword args"], "answer": 2},
        ],
        "Chase Level": [
            {"q": "What is a Python generator?",
             "choices": ["A list", "Lazy iterator using yield", "A dict", "A class"], "answer": 1},
            {"q": "What does `@staticmethod` do?",
             "choices": ["Makes read-only", "Method with no self/cls", "Private method", "Inherited method"], "answer": 1},
            {"q": "What is the time complexity of dict lookup in Python?",
             "choices": ["O(n)", "O(log n)", "O(1)", "O(n²)"], "answer": 2},
            {"q": "What does `__dunder__` mean?",
             "choices": ["Private", "Deleted", "Magic/special method", "Module"], "answer": 2},
            {"q": "What is a decorator in Python?",
             "choices": ["A comment style", "A class type", "Function wrapping function", "A list method"], "answer": 2},
            {"q": "What does `yield` do vs `return`?",
             "choices": ["Same thing", "Pauses and resumes", "Raises exception", "Imports module"], "answer": 1},
            {"q": "What is `__slots__` used for?",
             "choices": ["Define methods", "Restrict attributes to save memory", "Inherit class", "Set priority"], "answer": 1},
            {"q": "What is the GIL in Python?",
             "choices": ["Graphics layer", "Global Interpreter Lock", "Generator Init Loop", "Group Import List"], "answer": 1},
        ],
    },

    "Ruby": {
        "Beginner": [
            {"q": "How do you print in Ruby?",
             "choices": ["console.log()", "print()", "puts", "echo"], "answer": 2},
            {"q": "What symbol defines a string in Ruby?",
             "choices": ["#", "@", "\"", "$"], "answer": 2},
            {"q": "What does `nil` mean in Ruby?",
             "choices": ["Zero", "Empty string", "Nothing/null", "Error"], "answer": 2},
            {"q": "How do you define a method in Ruby?",
             "choices": ["func", "def", "method", "fun"], "answer": 1},
            {"q": "What is a Ruby symbol?",
             "choices": ["A number", "Immutable identifier with :", "A comment", "A variable"], "answer": 1},
            {"q": "What keyword ends a block in Ruby?",
             "choices": ["stop", "close", "end", "finish"], "answer": 2},
            {"q": "How do you create an array in Ruby?",
             "choices": ["{1,2}", "[1,2]", "(1,2)", "<1,2>"], "answer": 1},
            {"q": "What does `.length` return on a string?",
             "choices": ["Words", "Bytes", "Characters count", "Lines"], "answer": 2},
        ],
        "Medium": [
            {"q": "What is a Ruby block?",
             "choices": ["A class", "Code between do..end or {}", "A method", "An import"], "answer": 1},
            {"q": "What does `yield` do in Ruby?",
             "choices": ["Returns value", "Calls the passed block", "Imports module", "Raises error"], "answer": 1},
            {"q": "What is `attr_accessor` used for?",
             "choices": ["Import", "Creates getter and setter", "Define module", "Add method"], "answer": 1},
            {"q": "What is the difference between `==` and `.equal?` in Ruby?",
             "choices": ["None", "== value equality, .equal? object identity", "Opposite", "Only for numbers"], "answer": 1},
            {"q": "What does `map` do to an array?",
             "choices": ["Sort", "Filter", "Transform each element", "Delete"], "answer": 2},
            {"q": "What is a Ruby module?",
             "choices": ["A class", "A namespace/mixin", "A variable", "A file"], "answer": 1},
            {"q": "What does `rescue` do in Ruby?",
             "choices": ["Exit program", "Handle exceptions", "Import file", "Define loop"], "answer": 1},
            {"q": "How do you call a parent method in Ruby?",
             "choices": ["parent()", "super", "base()", "extend"], "answer": 1},
        ],
        "Chase Level": [
            {"q": "What is the difference between `Proc` and `Lambda` in Ruby?",
             "choices": ["Same thing", "Lambda checks args/returns differ", "Proc is faster", "Lambda is a class"], "answer": 1},
            {"q": "What does `freeze` do to an object in Ruby?",
             "choices": ["Copy it", "Make it immutable", "Delete it", "Convert to string"], "answer": 1},
            {"q": "What is metaprogramming in Ruby?",
             "choices": ["Writing fast code", "Code that writes code", "Module imports", "Class inheritance"], "answer": 1},
            {"q": "What does `method_missing` do?",
             "choices": ["Raises error", "Called when method not found", "Imports method", "Creates method"], "answer": 1},
            {"q": "What is `ObjectSpace` in Ruby?",
             "choices": ["Memory manager", "All living objects namespace", "A gem", "A module type"], "answer": 1},
            {"q": "What is `Comparable` module used for?",
             "choices": ["Sorting/comparing objects via <=>", "File I/O", "String ops", "Threading"], "answer": 0},
            {"q": "What does `tap` do in Ruby?",
             "choices": ["Touch screen input", "Passes object to block then returns it", "Closes file", "Formats string"], "answer": 1},
            {"q": "What is `Fiber` in Ruby?",
             "choices": ["Network library", "Lightweight coroutine", "A gem", "A data structure"], "answer": 1},
        ],
    },

    "Arduino": {
        "Beginner": [
            {"q": "Which function runs once at startup in Arduino?",
             "choices": ["loop()", "start()", "setup()", "begin()"], "answer": 2},
            {"q": "Which function runs repeatedly in Arduino?",
             "choices": ["setup()", "repeat()", "loop()", "run()"], "answer": 2},
            {"q": "What does `pinMode(13, OUTPUT)` do?",
             "choices": ["Read pin 13", "Set pin 13 as output", "Delete pin 13", "Rename pin 13"], "answer": 1},
            {"q": "What does `digitalWrite(13, HIGH)` do?",
             "choices": ["Read voltage", "Set pin 13 to 5V/ON", "Lower pin 13", "Reset board"], "answer": 1},
            {"q": "What does `delay(1000)` do?",
             "choices": ["Wait 1 second", "Wait 1ms", "Speed up", "Loop 1000 times"], "answer": 0},
            {"q": "What is the Arduino language based on?",
             "choices": ["Python", "Java", "C/C++", "Ruby"], "answer": 2},
            {"q": "What does `Serial.begin(9600)` do?",
             "choices": ["Start Wi-Fi", "Open serial at 9600 baud", "Connect Bluetooth", "Reset chip"], "answer": 1},
            {"q": "What does `analogRead(A0)` return?",
             "choices": ["0 or 1", "0 to 255", "0 to 1023", "0 to 5"], "answer": 2},
        ],
        "Medium": [
            {"q": "What is PWM used for on Arduino?",
             "choices": ["Digital on/off", "Simulating analog output", "Power supply", "Wi-Fi"], "answer": 1},
            {"q": "What does `analogWrite(pin, 128)` do?",
             "choices": ["Full power", "Half power via PWM", "Turn off", "Read value"], "answer": 1},
            {"q": "What is a pull-up resistor used for?",
             "choices": ["Boost power", "Default HIGH state on input", "Filter noise", "Ground pin"], "answer": 1},
            {"q": "What is `millis()` used for?",
             "choices": ["Get RAM", "Get time since boot in ms", "CPU speed", "Pin number"], "answer": 1},
            {"q": "What does `I2C` stand for?",
             "choices": ["Inter-Integrated Circuit", "Internal Interface Circuit", "Input/Output Control", "Instant Interface"], "answer": 0},
            {"q": "How many analog pins does standard Arduino Uno have?",
             "choices": ["2", "4", "6", "8"], "answer": 2},
            {"q": "What does `map(val, 0, 1023, 0, 255)` do?",
             "choices": ["Copy array", "Remap val from one range to another", "Create map", "Print val"], "answer": 1},
            {"q": "What is a servo motor controlled by in Arduino?",
             "choices": ["Voltage", "Frequency", "PWM pulse width", "Resistance"], "answer": 2},
        ],
        "Chase Level": [
            {"q": "What is the difference between SRAM and Flash on Arduino?",
             "choices": ["No difference", "SRAM=runtime data, Flash=program storage", "Flash is RAM", "SRAM stores program"], "answer": 1},
            {"q": "What does `volatile` keyword do in Arduino C?",
             "choices": ["Encrypt variable", "Prevent compiler optimizing ISR vars", "Delete on reset", "Make constant"], "answer": 1},
            {"q": "What is an ISR in Arduino?",
             "choices": ["Interrupt Service Routine", "Input Signal Register", "Internal Serial Rate", "Index Sort Routine"], "answer": 0},
            {"q": "What does `attachInterrupt(0, ISR, RISING)` do?",
             "choices": ["Delete interrupt", "Attach ISR to pin 0 on rising edge", "Set baud rate", "Power pin"], "answer": 1},
            {"q": "What is the watchdog timer used for?",
             "choices": ["Display time", "Reset system if it hangs", "Count loops", "Set PWM"], "answer": 1},
            {"q": "What is SPI used for?",
             "choices": ["Wi-Fi", "High-speed synchronous serial comms", "Analog input", "Power regulation"], "answer": 1},
            {"q": "What does `PROGMEM` do?",
             "choices": ["Program memory wipe", "Store const data in Flash not SRAM", "CPU profiling", "Debug mode"], "answer": 1},
            {"q": "What is bit masking used for in Arduino?",
             "choices": ["Hide data", "Read/set specific bits in register", "Encrypt serial", "Filter audio"], "answer": 1},
        ],
    },
}